[package]
description = "Bindings to LLVM's C API"
documentation = "http://rustdoc.taricorp.net/llvm-sys/llvm_sys/"
repository = "https://bitbucket.org/tari/llvm-sys.rs"
readme = "README.md"
license = "MIT"
keywords = ["bindings", "llvm"]
categories = ["external-ffi-bindings"]
links = "llvm"
name = "llvm-sys"
version = "50.0.4"
authors = [
  "Peter Marheine <peter@taricorp.net>",
  "Scott Olson <scott@solson.me>",
]
build = "build.rs"

[badges]
appveyor = { service = "bitbucket", repository = "tari/llvm-sys.rs", branch = "default" }

[features]
strict-versioning = []

[dependencies]
libc = "0.2"

[build-dependencies]
gcc = "0.3.53"
lazy_static = "0.2.1"
regex = "0.2"
semver = "0.6"
